# POSTTEST 7

In [1]:
import tensorflow as tf

buat nilai random dengan shape(5,5) dalam variable random_tensor

In [2]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1).numpy()
random_tensor

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

buat nilai prima dengan shape(5,5) dalam variable prime_tensor

In [3]:
prime_tensor = [[2,3,5,7,11],[7,11,13,17,19],[17,19,23,29,31],[29,31,37,41,47],[41,43,47,53,59]]
prime_tensor

prime_tensor_dimension = tf.convert_to_tensor(prime_tensor, dtype=tf.int64)

tampilkan dimensi kedua tabel

In [4]:
random_tensor.shape

(5, 5)

In [6]:
prime_tensor_dimension.shape

TensorShape([5, 5])

# ARITMATIKA 

perintah aritmatika penjumlahan, pengurangan, perkalian, pembagian, pangkat

In [7]:
tf.add(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.1886818,  4.4845986,  5.0653296,  4.557296 , 11.099248 ],
       [ 7.591224 , 11.592823 , 10.87707  , 16.277103 , 18.94373  ],
       [17.643545 , 18.735676 , 24.856632 , 29.567842 , 30.617165 ],
       [27.514656 , 32.261772 , 36.974693 , 40.73537  , 48.532814 ],
       [39.257023 , 42.562107 , 46.43399  , 53.32067  , 60.13283  ]],
      dtype=float32)>

In [8]:
tf.subtract(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -2.8113182,  -1.5154012,  -4.9346704,  -9.442704 , -10.900752 ],
       [ -6.408776 , -10.407177 , -15.12293  , -17.722897 , -19.05627  ],
       [-16.356455 , -19.264324 , -21.143368 , -28.432158 , -31.382835 ],
       [-30.485344 , -29.73823  , -37.025307 , -41.26463  , -45.467186 ],
       [-42.742977 , -43.437893 , -47.56601  , -52.67933  , -57.86717  ]],
      dtype=float32)>

In [9]:
tf.multiply(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -1.6226364 ,   4.4537964 ,   0.32664686, -17.09893   ,
          1.0917324 ],
       [  4.1385703 ,   6.521053  , -27.598083  , -12.289253  ,
         -1.0691372 ],
       [ 10.940262  ,  -5.022157  ,  42.702564  ,  16.46741   ,
        -11.867912  ],
       [-43.074955  ,  39.114902  ,  -0.93632495, -10.849817  ,
         72.04225   ],
       [-71.46207   , -18.829397  , -26.60247   ,  16.99547   ,
         66.83703   ]], dtype=float32)>

In [10]:
tf.divide(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.4056591 ,  0.49486625,  0.01306587, -0.34895775,  0.00902258],
       [ 0.08446062,  0.053893  , -0.16330227, -0.04252337, -0.0029616 ],
       [ 0.03785558, -0.01391179,  0.08072318,  0.01958075, -0.01234955],
       [-0.05121874,  0.04070229, -0.00068395, -0.00645438,  0.03261306],
       [-0.04251164, -0.01018356, -0.01204277,  0.00605036,  0.01920052]],
      dtype=float32)>

In [11]:
tf.pow(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 6.5823728e-01,  3.2721055e+00,  1.1899876e-06, -5.1891492e+02,
         9.2036214e-12],
       [ 2.5250269e-02,  3.1781562e-03, -1.7789455e+04, -4.0206988e-03,
        -1.8001847e-24],
       [ 5.5697956e-04, -1.0485702e-11,  1.5160045e+06,  7.4574679e-08,
        -1.1841103e-13],
       [-9.6156516e+04,  1.3501986e+03, -0.0000000e+00, -2.1290281e-24,
         5.2239824e+08],
       [-7.8155469e+09, -3.7915929e-16, -2.4139753e-12,  6.6227554e-27,
         1.5694297e+03]], dtype=float32)>

# MIN MAX

menampilkan nilai max dan min dari random_tensor

In [12]:
tf.argmax(random_tensor, axis = 0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 0, 2, 2, 3], dtype=int64)>

In [13]:
tf.argmin(random_tensor, axis = 0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 4, 1, 0, 2], dtype=int64)>

# CONCATENATION

menampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor

In [14]:
concated_sample_1 = tf.concat([random_tensor,prime_tensor],axis=0)
print("size of the concatenated data:",concated_sample_1)

size of the concatenated data: tf.Tensor(
[[-8.1131822e-01  1.4845988e+00  6.5329373e-02 -2.4427042e+00
   9.9248402e-02]
 [ 5.9122431e-01  5.9282297e-01 -2.1229296e+00 -7.2289723e-01
  -5.6270380e-02]
 [ 6.4354479e-01 -2.6432407e-01  1.8566332e+00  5.6784171e-01
  -3.8283589e-01]
 [-1.4853433e+00  1.2617711e+00 -2.5306080e-02 -2.6462969e-01
   1.5328138e+00]
 [-1.7429771e+00 -4.3789294e-01 -5.6601000e-01  3.2066926e-01
   1.1328310e+00]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 7.0000000e+00  1.1000000e+01  1.3000000e+01  1.7000000e+01
   1.9000000e+01]
 [ 1.7000000e+01  1.9000000e+01  2.3000000e+01  2.9000000e+01
   3.1000000e+01]
 [ 2.9000000e+01  3.1000000e+01  3.7000000e+01  4.1000000e+01
   4.7000000e+01]
 [ 4.1000000e+01  4.3000000e+01  4.7000000e+01  5.3000000e+01
   5.9000000e+01]], shape=(10, 5), dtype=float32)


# SORTING DESCENDING

menampilkan sorting descending dari variable random_tensor

In [15]:
tf.argsort(random_tensor,direction="DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[1, 4, 2, 0, 3],
       [1, 0, 4, 3, 2],
       [2, 0, 3, 1, 4],
       [4, 1, 2, 3, 0],
       [4, 3, 1, 2, 0]])>

menampilkan sorting descending dari variable prime_tensor

In [16]:
tf.argsort(prime_tensor,direction="DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0]])>