# POSTTEST 7

In [24]:
import tensorflow as tf

buat nilai random dengan shape(5,5) dalam variable random_tensor

In [41]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1).numpy()
random_tensor

array([[ 0.00534202, -1.0460438 , -1.6427648 , -0.3495337 ,  0.951451  ],
       [ 0.8105827 , -0.761741  ,  1.0136645 , -1.8470215 ,  0.20171778],
       [ 1.2173525 , -1.7574261 ,  1.765832  ,  1.14004   ,  0.8317814 ],
       [-1.9974602 ,  0.25176758,  1.0689832 ,  0.30159846,  0.2641973 ],
       [ 0.02316601,  0.7222838 ,  0.3744623 , -0.09558094,  1.4185706 ]],
      dtype=float32)

buat nilai prima dengan shape(5,5) dalam variable prime_tensor

In [54]:
prime_tensor = [[2,3,5,7,11],[7,11,13,17,19],[17,19,23,29,31],[29,31,37,41,47],[41,43,47,53,59]]
prime_tensor

prime_tensor_dimension = tf.convert_to_tensor(prime_tensor, dtype=tf.int64)

tampilkan dimensi kedua tabel

In [55]:
random_tensor.shape

(5, 5)

In [53]:
a.shape

TensorShape([5, 5])

# ARITMATIKA 

perintah aritmatika penjumlahan, pengurangan, perkalian, pembagian, pangkat

In [43]:
tf.add(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.005342 ,  1.9539562,  3.3572352,  6.6504664, 11.951451 ],
       [ 7.8105826, 10.238259 , 14.013664 , 15.152979 , 19.201717 ],
       [18.217352 , 17.242575 , 24.765831 , 30.14004  , 31.831781 ],
       [27.00254  , 31.251768 , 38.068985 , 41.301598 , 47.2642   ],
       [41.023167 , 43.722282 , 47.374462 , 52.90442  , 60.41857  ]],
      dtype=float32)>

In [44]:
tf.subtract(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -1.994658 ,  -4.046044 ,  -6.642765 ,  -7.3495336, -10.048549 ],
       [ -6.1894174, -11.761741 , -11.986336 , -18.847021 , -18.798283 ],
       [-15.782647 , -20.757425 , -21.234169 , -27.85996  , -30.168219 ],
       [-30.99746  , -30.748232 , -35.931015 , -40.698402 , -46.7358   ],
       [-40.976833 , -42.277718 , -46.625538 , -53.09558  , -57.58143  ]],
      dtype=float32)>

In [46]:
tf.multiply(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.0684047e-02, -3.1381311e+00, -8.2138243e+00, -2.4467359e+00,
         1.0465961e+01],
       [ 5.6740789e+00, -8.3791504e+00,  1.3177638e+01, -3.1399364e+01,
         3.8326378e+00],
       [ 2.0694992e+01, -3.3391098e+01,  4.0614136e+01,  3.3061161e+01,
         2.5785223e+01],
       [-5.7926346e+01,  7.8047948e+00,  3.9552380e+01,  1.2365537e+01,
         1.2417273e+01],
       [ 9.4980657e-01,  3.1058203e+01,  1.7599728e+01, -5.0657902e+00,
         8.3695671e+01]], dtype=float32)>

In [47]:
tf.divide(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.00267101, -0.34868124, -0.32855296, -0.04993339,  0.08649555],
       [ 0.11579753, -0.06924918,  0.07797419, -0.10864832,  0.01061673],
       [ 0.07160897, -0.09249611,  0.0767753 ,  0.03931173,  0.02683166],
       [-0.06887794,  0.00812153,  0.02889144,  0.00735606,  0.00562122],
       [ 0.00056502,  0.0167973 ,  0.00796728, -0.00180341,  0.02404357]],
      dtype=float32)>

In [48]:
tf.pow(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.8537215e-05, -1.1445889e+00, -1.1964015e+01, -6.3741673e-04,
         5.7842988e-01],
       [ 2.2992241e-01, -5.0104938e-02,  1.1929575e+00, -3.3886211e+04,
         6.1679293e-14],
       [ 2.8319008e+01, -4.4943258e+04,  4.7844884e+05,  4.4738667e+01,
         3.3134860e-03],
       [-5.1744739e+08,  2.6977007e-19,  1.1801101e+01,  4.5351732e-22,
         6.7706886e-28],
       [ 0.0000000e+00,  8.4030722e-07,  8.9162259e-21, -0.0000000e+00,
         9.1034714e+08]], dtype=float32)>

# MIN MAX

menampilkan nilai max dan min dari random_tensor

In [28]:
tf.argmax(random_tensor, axis = 0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 0, 3, 0, 2], dtype=int64)>

In [29]:
tf.argmin(random_tensor, axis = 0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 3, 4, 1, 4], dtype=int64)>

# CONCATENATION

menampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor

In [42]:
concated_sample_1 = tf.concat([random_tensor,prime_tensor],axis=0)
print("size of the concatenated data:",concated_sample_1)

size of the concatenated data: tf.Tensor(
[[ 5.3420234e-03 -1.0460438e+00 -1.6427648e+00 -3.4953371e-01
   9.5145100e-01]
 [ 8.1058270e-01 -7.6174098e-01  1.0136645e+00 -1.8470215e+00
   2.0171778e-01]
 [ 1.2173525e+00 -1.7574261e+00  1.7658319e+00  1.1400400e+00
   8.3178139e-01]
 [-1.9974602e+00  2.5176758e-01  1.0689832e+00  3.0159846e-01
   2.6419729e-01]
 [ 2.3166014e-02  7.2228378e-01  3.7446231e-01 -9.5580943e-02
   1.4185706e+00]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 7.0000000e+00  1.1000000e+01  1.3000000e+01  1.7000000e+01
   1.9000000e+01]
 [ 1.7000000e+01  1.9000000e+01  2.3000000e+01  2.9000000e+01
   3.1000000e+01]
 [ 2.9000000e+01  3.1000000e+01  3.7000000e+01  4.1000000e+01
   4.7000000e+01]
 [ 4.1000000e+01  4.3000000e+01  4.7000000e+01  5.3000000e+01
   5.9000000e+01]], shape=(10, 5), dtype=float32)


# SORTING DESCENDING

menampilkan sorting descending dari variable random_tensor

In [31]:
tf.argsort(random_tensor,direction="DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[2, 1, 3, 4, 0],
       [2, 1, 4, 0, 3],
       [2, 0, 4, 1, 3],
       [2, 3, 4, 0, 1],
       [3, 1, 2, 0, 4]])>

menampilkan sorting descending dari variable prime_tensor

In [32]:
tf.argsort(prime_tensor,direction="DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0]])>